// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAPS_App.Context;

#nullable disable

namespace SAPS_App.Migrations.SAPS_
{
    [DbContext(typeof(SAPS_Context))]
    partial class SAPS_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAPS_App.Models.CaseManager", b =>
                {
                    b.Property<int>("CaseManagerNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseManagerNo"));

                    b.Property<string>("CaseManagerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaseManagerNo");

                    b.ToTable("Case_Managers");
                });

            modelBuilder.Entity("SAPS_App.Models.CriminalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaseManagerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CaseManagerNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IssuerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OffenceCommited")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuspectNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaseManagerNo");

                    b.HasIndex("SuspectNumber");

                    b.ToTable("CriminalRecords");
                });

            modelBuilder.Entity("SAPS_App.Models.Offences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Offences");
                });

            modelBuilder.Entity("SAPS_App.Models.PoliceStations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PoliceStations");
                });

            modelBuilder.Entity("SAPS_App.Models.Suspect", b =>
                {
                    b.Property<int>("SuspectNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuspectNumber"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SuspectId")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("SuspectNumber");

                    b.ToTable("Suspects");
                });

            modelBuilder.Entity("SAPS_App.Models.SuspectSearch", b =>
                {
                    b.Property<int>("SuspectNumber")
                        .HasColumnType("int");

                    b.HasIndex("SuspectNumber");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("SAPS_App.Models.CriminalRecord", b =>
                {
                    b.HasOne("SAPS_App.Models.CaseManager", "CaseManager")
                        .WithMany("CriminalRecords")
                        .HasForeignKey("CaseManagerNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAPS_App.Models.Suspect", "Suspect")
                        .WithMany("CriminalRecords")
                        .HasForeignKey("SuspectNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseManager");

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("SAPS_App.Models.SuspectSearch", b =>
                {
                    b.HasOne("SAPS_App.Models.Suspect", "Suspect")
                        .WithMany()
                        .HasForeignKey("SuspectNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("SAPS_App.Models.CaseManager", b =>
                {
                    b.Navigation("CriminalRecords");
                });

            modelBuilder.Entity("SAPS_App.Models.Suspect", b =>
                {
                    b.Navigation("CriminalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
